// Palette Drill: 30 briefs, each written from a real product. The product's
// name stays hidden until the reveal. One brief per day; a skipped day is
// just skipped.
(function () {
  const START = new Date(2026, 9, 9); // Drill 1: 9 Oct 2026
  const DAY = 86400000;

  const B = (o) => o;
  const LIBRARY = [
    B({ id: "wise", product: "Wise", competitors: ["Revolut", "Monzo"], template: "mobile-list", mode: "light",
      what: "A multi-currency money app for expats, freelancers and international students.",
      positioning: "A challenger to the banks: it shows the real cost of sending money up front.",
      personality: "Plain-spoken, energetic, a little defiant.", avoid: "Not corporate, not too playful.",
      where: "The home screen: a balance per currency, recent transfers and one Send button.",
      statuses: ["Money received"], hard: "Looking defiant while a screen full of numbers stays calm.",
      copy: { title: "Home", cards: [["GBP", "£2,140.50"], ["EUR", "€860.12"], ["USD", "$415.00"]], section: "Transfers", more: "See all",
        rows: [["From Sam Ortega", "Today · EUR", "+€120.00", "a"], ["Rent", "Yesterday · GBP", "−£950.00"], ["From Lena Park", "Mon · USD", "+$80.00", "a"], ["Card top-up", "Sun · EUR", "−€40.00"], ["Groceries", "Sat · GBP", "−£32.10"]], cta: "Send money" } }),
    B({ id: "linear", product: "Linear", competitors: ["Jira", "Asana"], template: "desktop-table", mode: "light",
      what: "An issue tracker for fast-moving software teams.",
      positioning: "Project tracking that's as quick as the people using it.",
      personality: "Precise, fast, understated.", avoid: "Not enterprise grey, not playful.",
      where: "The issue list: titles, status pills, owners and a New issue button.",
      statuses: ["Done", "Blocked"], hard: "Being memorable with almost no color at all.",
      copy: { workspace: "Acme", nav: [["list", "Issues"], ["home", "Inbox"], ["grid", "Projects"], ["chart", "Cycles"], ["user", "Team"]], title: "Active issues", cta: "New issue", tabs: ["All issues", "Active", "Backlog"] } }),
    B({ id: "calm", product: "Calm", competitors: ["Headspace", "BetterSleep"], template: "mobile-onboarding", mode: "dark",
      what: "A sleep and relaxation app.",
      positioning: "Sleep better and stress less, starting tonight.",
      personality: "Serene, soft, enveloping.", avoid: "Not sleepy-dull, not spa cliché.",
      where: "The first welcome screen: a calming picture, a headline and Get started.",
      statuses: [], hard: "A dark screen that feels restful, not gloomy.",
      copy: { heading: "Take a deep breath", sub: "Sleep stories, soundscapes and short meditations to help you switch off.", cta: "Get started", cta2: "I already have an account" } }),
    B({ id: "notion", product: "Notion", competitors: ["Coda", "ClickUp"], template: "landing-hero", mode: "light",
      what: "An all-in-one workspace for notes, docs and projects.",
      positioning: "One tool for the whole team's thinking.",
      personality: "Simple, crafted, a little whimsical.", avoid: "Not corporate, not techy.",
      where: "The homepage hero: headline, two buttons and a product picture.",
      statuses: [], hard: "Whimsy that comes from restraint, not from lots of color.",
      copy: { brand: "Workspace", eyebrow: "New: AI meeting notes", heading: "Your wiki, docs and projects. Together.", sub: "One connected space for every team, with AI that knows your work.", cta: "Get it free", cta2: "Request a demo" } }),
    B({ id: "strava", product: "Strava", competitors: ["Nike Run Club", "Garmin Connect"], template: "mobile-detail", mode: "light",
      what: "A training app for runners and cyclists.",
      positioning: "Track every effort and share it with the people who push you.",
      personality: "Driven, competitive, outdoorsy.", avoid: "Not aggressive, not corporate.",
      where: "A run's summary: distance, a splits chart, stats, Share and Give kudos.",
      statuses: ["Personal best", "Slower than usual"], hard: "High energy without every element shouting.",
      copy: { title: "Morning Run", kicker: "Distance", big: "10.4 km", bigLabel: "Saturday · 52:18", change: "PR on 5 km", changeB: "Km 8 slower", chips: ["Splits", "Pace", "Heart"], stats: [["5:01", "Avg pace"], ["142", "Elev. m"], ["612", "Calories"]], chartTitle: "Pace per km", bars: [62, 70, 68, 74, 80, 72, 66, 48, 70, 78], note: "Felt strong after the first two kilometres. Windy along the river.", cta: "Give kudos", cta2: "Share" } }),
    B({ id: "mercury", product: "Mercury", competitors: ["Brex", "Ramp"], template: "desktop-dashboard", mode: "light",
      what: "Online banking for startups.",
      positioning: "Banking that feels built for founders, not for branches.",
      personality: "Refined, calm, trustworthy.", avoid: "Not flashy fintech, not an old bank.",
      where: "The account overview: balances, money in and out, a cash-flow chart and recent payments.",
      statuses: ["Money in", "Money out"], hard: "Premium and quiet without being cold.",
      copy: { workspace: "Northwind", nav: [["home", "Home"], ["list", "Transactions"], ["card", "Cards"], ["send", "Payments"], ["chart", "Insights"]], title: "Good morning", range: "Last 30 days", cta: "Move money",
        kpis: [["Total balance", "$1,284,500", "+$42,100", "a"], ["Money in", "$318,200", "+12%", "a"], ["Money out", "$276,100", "+9%", "b"], ["Runway", "26 months", "No change"]], chartTitle: "Cash flow", listTitle: "Recent payments" } }),
    B({ id: "monzo", product: "Monzo", competitors: ["Revolut", "Starling Bank"], template: "mobile-form", mode: "light",
      what: "A mobile bank for people who want to see where their money goes.",
      positioning: "Banking that's honest, friendly and on your side.",
      personality: "Bright, friendly, straightforward.", avoid: "Not childish, not stiff.",
      where: "Sending money: amount, recipient, reference, transfer speed and Continue.",
      statuses: ["Looks good", "Needs fixing"], hard: "Bright without making an error feel like a party.",
      copy: { title: "Send money", heading: "Who are you paying?", sub: "Payments to UK accounts usually arrive in seconds.", fields: [["Amount", "£250.00", "a", "You have £1,240 available"], ["Account number", "1234 567", "b", "Account numbers have 8 digits"], ["Reference", "Rent October"]], choices: ["Now", "Later", "Repeat"], choiceLabel: "When", cta: "Continue" } }),
    B({ id: "spotify", product: "Spotify", competitors: ["Apple Music", "SoundCloud"], template: "mobile-list", mode: "dark",
      what: "A music streaming app for people who listen all day.",
      positioning: "All your music, plus playlists that seem to know you.",
      personality: "Expressive, youthful, confident.", avoid: "Not nightclub neon, not muted.",
      where: "A playlist: summary cards, the track list and a Play button.",
      statuses: [], hard: "Making a dark screen feel alive without coloring every row.",
      copy: { title: "Daily Mix 1", cards: [["Tracks", "50 songs"], ["Length", "3 h 12 m"], ["Saves", "1.2M"]], section: "Tracks", more: "Shuffle",
        rows: [["Golden Hour", "JVKE", "3:29"], ["Sunroof", "Nicky Youre", "2:43"], ["Heat Waves", "Glass Animals", "3:58"], ["Levitating", "Dua Lipa", "3:23"], ["Ribs", "Lorde", "4:18"]], cta: "Play", nav: ["home", "search", "list", "user"] } }),
    B({ id: "figma", product: "Figma", competitors: ["Sketch", "Canva"], template: "pricing", mode: "light",
      what: "A collaborative design tool that runs in the browser.",
      positioning: "Design together, in real time, from anywhere.",
      personality: "Creative, collaborative, clear.", avoid: "Not a childish rainbow, not a grey tool.",
      where: "The pricing section: three plans, the middle one featured.",
      statuses: [], hard: "Creative energy that still reads as a serious purchase.",
      copy: { heading: "Choose the plan for your team", sub: "Start free. Add seats when your team grows.", plans: [["Starter", "$0", "For trying it out", ["3 design files", "Unlimited personal drafts", "Basic prototyping"], "Start free"], ["Professional", "$16", "For small teams", ["Unlimited files", "Shared libraries", "Advanced prototyping", "Dev handoff"], "Get Professional"], ["Organization", "$55", "For companies", ["Everything in Professional", "Design systems analytics", "Branching", "SSO"], "Contact sales"]] } }),
    B({ id: "duolingo", product: "Duolingo", competitors: ["Babbel", "Busuu"], template: "mobile-onboarding", mode: "light",
      what: "A language-learning app for anyone with five spare minutes.",
      positioning: "Learning a language should feel like a game you want to keep playing.",
      personality: "Bold, cheeky, encouraging.", avoid: "Not school, not babyish.",
      where: "The welcome screen: an illustration, a headline, Get started and I already have an account.",
      statuses: [], hard: "Loud and fun while the buttons still lead.",
      copy: { heading: "Learn a language for free. Forever.", sub: "Five minutes a day is all it takes to build the habit.", cta: "Get started", cta2: "I already have an account" } }),
    B({ id: "github", product: "GitHub", competitors: ["GitLab", "Bitbucket"], template: "desktop-table", mode: "dark",
      what: "A code hosting platform for developers.",
      positioning: "Where the world builds software together.",
      personality: "Technical, dependable, community-minded.", avoid: "Not flashy, not corporate.",
      where: "Pull requests: titles, status, reviewers and New pull request.",
      statuses: ["Merged", "Changes requested"], hard: "A dense dark table where status still pops.",
      copy: { workspace: "acme/web", nav: [["list", "Pull requests"], ["home", "Code"], ["bell", "Issues"], ["play", "Actions"], ["grid", "Projects"]], title: "Pull requests", cta: "New pull request", tabs: ["Open", "Merged", "Closed"], cols: ["Title", "Status", "Reviewer", "Updated"],
        rows: [["Add dark mode tokens", "Merged", "a"], ["Fix flaky checkout test", "Open"], ["Bump dependencies", "Changes requested", "b"], ["Cache build artifacts", "Merged", "a"], ["Refactor auth middleware", "Open"], ["Remove legacy API routes", "Changes requested", "b"], ["Docs: setup guide", "Draft"], ["Speed up CI matrix", "Merged", "a"]] } }),
    B({ id: "airbnb", product: "Airbnb", competitors: ["Booking.com", "Vrbo"], template: "mobile-detail", mode: "light",
      what: "A travel app for booking homes from local hosts.",
      positioning: "Stay somewhere that feels like it belongs to the place.",
      personality: "Welcoming, human, quietly premium.", avoid: "Not luxury-cold, not budget.",
      where: "A home's page: rating, highlights, a nights chart and Reserve.",
      statuses: ["Rare find"], hard: "One warm color that earns the Reserve tap.",
      copy: { title: "Lisbon loft", kicker: "Guest favourite", big: "4.96", bigLabel: "298 reviews · Alfama, Lisbon", change: "Rare find", chips: ["Photos", "Amenities", "Reviews"], stats: [["2", "Bedrooms"], ["4", "Guests"], ["1.5", "Baths"]], chartTitle: "Price per night this month", bars: [60, 58, 62, 75, 90, 88, 64], note: "Sunny loft with a terrace over the river. Host replies within an hour.", cta: "Reserve", cta2: "Save" } }),
    B({ id: "venmo", product: "Venmo", competitors: ["PayPal", "Zelle"], template: "mobile-form", mode: "light",
      what: "A payment app for splitting bills with friends.",
      positioning: "Paying people should feel as easy as texting them.",
      personality: "Social, casual, trustworthy.", avoid: "Not banking-stiff, not meme-y.",
      where: "Pay or request: amount, who, what it's for and Pay.",
      statuses: ["Confirmed", "Error"], hard: "Casual and friendly, yet clearly safe for money.",
      copy: { title: "Pay or request", heading: "Split the pizza", sub: "Friends get it instantly.", fields: [["Amount", "$18.50", "a", "Within your balance"], ["To", "", "b", "Pick someone to pay"], ["What's it for?", "Pizza Friday"]], choiceLabel: "Who can see", choices: ["Public", "Friends", "Private"], cta: "Pay" } }),
    B({ id: "stripe", product: "Stripe", competitors: ["PayPal", "Square"], template: "desktop-dashboard", mode: "light",
      what: "Payments infrastructure for internet businesses.",
      positioning: "The financial backbone businesses grow on.",
      personality: "Polished, precise, confident.", avoid: "Not banky, not startup-loud.",
      where: "The payments overview: volume, customers, refunds, a daily chart and recent charges.",
      statuses: ["Growth", "Decline"], hard: "Polish from a single color doing all the leading.",
      copy: { workspace: "Northwind", title: "Today", cta: "Create payment" } }),
    B({ id: "framer", product: "Framer", competitors: ["Webflow", "Wix"], template: "landing-hero", mode: "dark",
      what: "A website builder for designers.",
      positioning: "Design it and it's live. No developer needed.",
      personality: "Bold, creative, cutting-edge.", avoid: "Not gamer-ish, not corporate.",
      where: "The homepage hero: headline, two buttons and a product picture.",
      statuses: [], hard: "Cutting-edge on dark without neon everywhere.",
      copy: { brand: "Builder", eyebrow: "Now with AI layouts", heading: "Design websites that ship themselves", sub: "Go from idea to a live, fast site in one tool built for designers.", cta: "Start for free", cta2: "Watch the film", note: "Free plan forever. Custom domains from $5." } }),
    B({ id: "todoist", product: "Todoist", competitors: ["TickTick", "Any.do"], template: "mobile-list", mode: "light",
      what: "A to-do list app for people juggling work and life.",
      positioning: "Get everything out of your head and into one calm list.",
      personality: "Focused, tidy, quietly motivating.", avoid: "Not gamified, not sterile.",
      where: "Today: tasks with times and projects, and an Add task button.",
      statuses: ["Overdue"], hard: "Urgency for overdue tasks without making the list anxious.",
      copy: { title: "Today", cards: [["Today", "7 tasks"], ["Upcoming", "12 tasks"], ["Done", "4 today"]], section: "Tasks", more: "Sort",
        rows: [["Send invoice to Acme", "Work · 9:00", "Overdue", "a"], ["Call the dentist", "Personal · 11:30", "11:30"], ["Review Q4 plan", "Work · 14:00", "14:00"], ["Buy oat milk", "Errands", "Today"], ["Stretch for 10 minutes", "Health", "Today"]], cta: "Add task", nav: ["list", "home", "search", "user"] } }),
    B({ id: "oura", product: "Oura", competitors: ["WHOOP", "Fitbit"], template: "mobile-detail", mode: "dark",
      what: "A health app for a smart ring that tracks sleep and recovery.",
      positioning: "Know your body, one night at a time.",
      personality: "Calm, scientific, premium.", avoid: "Not sporty, not soft wellness.",
      where: "Last night's sleep: score, stages chart and stats.",
      statuses: ["Optimal", "Pay attention"], hard: "Status colors that inform without alarming at 7 am.",
      copy: { title: "Sleep", kicker: "Sleep score", big: "84", bigLabel: "7 h 42 m in bed · Good", change: "Optimal HRV", changeB: "Late bedtime", chips: ["Day", "Week", "Month"], stats: [["1 h 38", "Deep"], ["2 h 05", "REM"], ["58", "Resting HR"]], chartTitle: "Sleep stages", bars: [20, 55, 80, 45, 70, 90, 35, 60], note: "You went to bed 52 minutes later than usual. Try winding down earlier tonight.", cta: "Start wind-down", cta2: "Details" } }),
    B({ id: "airtable", product: "Airtable", competitors: ["Smartsheet", "monday.com"], template: "desktop-table", mode: "light",
      what: "A spreadsheet-database tool for operations teams.",
      positioning: "The power of a database with the ease of a spreadsheet.",
      personality: "Colorful, capable, friendly.", avoid: "Not toy-like, not IT software.",
      where: "A grid of records: names, status, owners and Add record.",
      statuses: ["Approved", "Needs changes"], hard: "Colorful that still scans like a serious tool.",
      copy: { workspace: "Ops base", nav: [["grid", "Grid"], ["list", "Kanban"], ["chart", "Interfaces"], ["bell", "Automations"], ["user", "Share"]], title: "Content calendar", cta: "Add record", tabs: ["Grid view", "This week", "Mine"] } }),
    B({ id: "flo", product: "Flo", competitors: ["Clue", "Natural Cycles"], template: "mobile-onboarding", mode: "light",
      what: "A period and cycle tracking app.",
      positioning: "Understand your body with predictions you can trust.",
      personality: "Caring, supportive, confident.", avoid: "Not clinical, not pink by default.",
      where: "The welcome screen: an illustration, a headline and Get started.",
      statuses: [], hard: "Gentle without falling back on the obvious pink.",
      copy: { heading: "Know your cycle, know yourself", sub: "Accurate predictions and answers from doctors, all private to you.", cta: "Get started", cta2: "Log in" } }),
    B({ id: "slack", product: "Slack", competitors: ["Microsoft Teams", "Discord"], template: "pricing", mode: "light",
      what: "A messaging app for work.",
      positioning: "Where work happens, together.",
      personality: "Friendly, productive, human.", avoid: "Not corporate blue, not teenage chat.",
      where: "The pricing section: three plans, the middle one featured.",
      statuses: [], hard: "Friendly color on a page about money and seats.",
      copy: { heading: "Plans for every team", sub: "Pay only for active members.", plans: [["Free", "$0", "For small teams trying it", ["90 days of history", "1:1 huddles", "10 integrations"], "Get started"], ["Pro", "$8.75", "For growing teams", ["Unlimited history", "Group huddles", "Unlimited apps", "Canvases"], "Upgrade to Pro"], ["Business+", "$15", "For larger companies", ["Everything in Pro", "SAML SSO", "Data exports", "99.99% uptime"], "Talk to sales"]] } }),
    B({ id: "coinbase", product: "Coinbase", competitors: ["Kraken", "Crypto.com"], template: "mobile-detail", mode: "dark",
      what: "A crypto trading app for everyday investors.",
      positioning: "Crypto made trustworthy enough for your savings.",
      personality: "Secure, precise, modern.", avoid: "Not a casino, not a 90s bank.",
      where: "An asset page: price, change, chart and Buy / Sell.",
      statuses: ["Price up", "Price down"], hard: "Up and down colors that read as equals, not a fight.",
      copy: { title: "Bitcoin", kicker: "BTC price", big: "$76,418", bigLabel: "Updated 10:30", change: "+0.68% today", changeB: "−2.1% this week", chips: ["1H", "1D", "1W"], stats: [["$1.5T", "Market cap"], ["$32B", "Volume"], ["0.0042", "You hold"]], chartTitle: "Price", bars: [55, 60, 52, 68, 74, 70, 82, 78, 85, 80], note: "Prices move fast. Set a limit order to buy at the price you choose.", cta: "Buy", cta2: "Sell" } }),
    B({ id: "calendly", product: "Calendly", competitors: ["Cal.com", "Doodle"], template: "mobile-form", mode: "light",
      what: "A scheduling tool that lets people book time with you.",
      positioning: "No more back-and-forth emails to find a time.",
      personality: "Efficient, professional, approachable.", avoid: "Not stiff, not cute.",
      where: "Booking details: name, email, notes and Schedule event.",
      statuses: ["Valid", "Required"], hard: "Approachable while it still looks like business software.",
      copy: { title: "30 min intro call", step: "Step 2 of 2", progress: 100, heading: "Enter your details", sub: "Tue, 14 Oct · 10:00–10:30", fields: [["Email", "ana@northwind.co", "a", "We'll send the invite here"], ["Name", "", "b", "Name is required"], ["Notes", "Optional"]], choiceLabel: "Meeting via", choices: ["Zoom", "Phone", "In person"], noteText: "You can reschedule or cancel from the invite at any time.", cta: "Schedule event" } }),
    B({ id: "vercel", product: "Vercel", competitors: ["Netlify", "Render"], template: "desktop-dashboard", mode: "dark",
      what: "A hosting platform for front-end developers.",
      positioning: "Ship your site and see it live in seconds.",
      personality: "Minimal, sharp, high-contrast.", avoid: "Not colorful, not cold.",
      where: "The project overview: deploys, requests, errors, a traffic chart and recent deployments.",
      statuses: ["Ready", "Error"], hard: "Almost all neutral, so the few colors carry everything.",
      copy: { workspace: "acme", nav: [["grid", "Projects"], ["play", "Deployments"], ["chart", "Analytics"], ["list", "Logs"], ["bell", "Settings"]], title: "Overview", cta: "Deploy",
        kpis: [["Deployments", "128", "All ready", "a"], ["Requests", "2.4M", "+18%", "a"], ["Errors", "312", "+4%", "b"], ["P75 load", "0.9 s", "−0.1 s"]], chartTitle: "Requests per day", listTitle: "Recent deployments", list: [["web · main", "Ready"], ["docs · main", "Ready"], ["web · fix-nav", "Building"], ["api · main", "Ready"]] } }),
    B({ id: "headspace", product: "Headspace", competitors: ["Calm", "Insight Timer"], template: "mobile-detail", mode: "light",
      what: "A meditation app for beginners with busy minds.",
      positioning: "Mindfulness made friendly and doable in a few minutes a day.",
      personality: "Warm, optimistic, gently playful.", avoid: "Not mystical, not clinical.",
      where: "Your week of practice: minutes, a daily chart, streak and Start session.",
      statuses: [], hard: "Warmth without turning the screen into a toy.",
      copy: { title: "Your week", kicker: "Mindful minutes", big: "84", bigLabel: "minutes this week", chips: ["Week", "Month", "Year"], stats: [["6", "Sessions"], ["4", "Day streak"], ["14", "Avg. minutes"]], chartTitle: "Minutes per day", bars: [40, 70, 0, 55, 90, 60, 35], note: "Nice work. Two more sessions and you'll match your best week.", cta: "Start session", cta2: "Share" } }),
    B({ id: "mailchimp", product: "Mailchimp", competitors: ["Klaviyo", "HubSpot"], template: "landing-hero", mode: "light",
      what: "An email marketing platform for small businesses.",
      positioning: "Marketing that helps small businesses look big.",
      personality: "Bold, quirky, warm.", avoid: "Not salesy, not generic SaaS.",
      where: "The homepage hero: headline, two buttons and a product picture.",
      statuses: [], hard: "Quirky character that doesn't fight the sign-up button.",
      copy: { brand: "Campaigns", eyebrow: "Small business week", heading: "Turn emails into revenue", sub: "Smart email and SMS tools that help small businesses sell more.", cta: "Start free trial", cta2: "See plans", note: "Free for up to 500 contacts." } }),
    B({ id: "ubereats", product: "Uber Eats", competitors: ["DoorDash", "Deliveroo"], template: "mobile-list", mode: "light",
      what: "A food delivery app for busy city people.",
      positioning: "Whatever you're craving, at your door fast.",
      personality: "Quick, confident, appetising.", avoid: "Not childish, not fine dining.",
      where: "Restaurants near you: delivery times, offers and one Order button.",
      statuses: ["Free delivery"], hard: "Appetising color in a screen that is mostly photos and text.",
      copy: { title: "Delivery", cards: [["Pizza", "38 places"], ["Sushi", "21 places"], ["Burgers", "44 places"]], section: "Near you", more: "Map",
        rows: [["Napoli Express", "Pizza · 4.7", "Free delivery", "a"], ["Sora Sushi", "Japanese · 4.8", "25 min"], ["Green Bowl", "Healthy · 4.6", "Free delivery", "a"], ["Burger Lab", "American · 4.5", "30 min"], ["Taco Norte", "Mexican · 4.6", "20 min"]], cta: "View basket · 2 items", nav: ["home", "search", "list", "user"] } }),
    B({ id: "hinge", product: "Hinge", competitors: ["Bumble", "Tinder"], template: "mobile-onboarding", mode: "light",
      what: "A dating app for people who want something real.",
      positioning: "The dating app designed to be deleted.",
      personality: "Thoughtful, warm, grown-up.", avoid: "Not flirty neon, not a matrimony site.",
      where: "The welcome screen: a picture, a headline, Create account and Sign in.",
      statuses: [], hard: "Grown-up without being beige.",
      copy: { heading: "Meet people worth deleting the app for", sub: "Profiles built on prompts and photos, so conversations start easier.", cta: "Create account", cta2: "Sign in" } }),
    B({ id: "amplitude", product: "Amplitude", competitors: ["Mixpanel", "PostHog"], template: "desktop-dashboard", mode: "light",
      what: "A product analytics tool for product teams.",
      positioning: "See what users do, and why.",
      personality: "Smart, energetic, data-forward.", avoid: "Not dashboard grey, not rainbow.",
      where: "A dashboard: active users, conversion, churn, a chart and top events.",
      statuses: ["Up", "Down"], hard: "Chart color that leads without a rainbow.",
      copy: { workspace: "Product", nav: [["chart", "Dashboards"], ["list", "Charts"], ["user", "Cohorts"], ["play", "Replays"], ["grid", "Data"]], title: "Growth dashboard", cta: "Share",
        kpis: [["Weekly actives", "48,210", "+6.4%", "a"], ["Activation", "41%", "+2.1 pts", "a"], ["Churn", "3.8%", "+0.6 pts", "b"], ["Sessions / user", "4.2", "No change"]], chartTitle: "Weekly active users", listTitle: "Top events", list: [["Sign up", "12,840"], ["Create project", "8,210"], ["Invite teammate", "3,904"], ["Upgrade", "1,120"]] } }),
    B({ id: "lemonade", product: "Lemonade", mobbin: "Lemonade Insurance", competitors: ["Hippo", "Root Insurance"], template: "mobile-form", mode: "light",
      what: "An insurance app for renters and homeowners.",
      positioning: "Insurance that's fast, fair and actually pleasant.",
      personality: "Playful, transparent, modern.", avoid: "Not childish, not a stuffy insurer.",
      where: "Getting a quote: address, move-in date, coverage and Continue.",
      statuses: ["Looks good", "Fix this"], hard: "Playful without losing trust on a form about money.",
      copy: { title: "Get a quote", heading: "Where do you live?", sub: "Your quote is ready in about 90 seconds.", fields: [["Address", "12 Elm Street, Apt 4", "a", "We cover this area"], ["Move-in date", "", "b", "Pick a date"], ["Unit", "Optional"]], choiceLabel: "Coverage", choices: ["Basic", "Plus", "Max"], noteText: "No paperwork. You can cancel at any time and get a refund.", cta: "Check my price" } }),
    B({ id: "dropbox", product: "Dropbox", competitors: ["Google Drive", "Box"], template: "pricing", mode: "dark",
      what: "Cloud storage for files and creative work.",
      positioning: "Keep everything you make safe and in one place.",
      personality: "Creative, reliable, simple.", avoid: "Not IT, not arty-messy.",
      where: "The pricing section: three plans, the middle one featured.",
      statuses: [], hard: "Reliable on dark while the featured plan still glows.",
      copy: { heading: "Find the right plan", sub: "Try any plan free for 30 days.", plans: [["Plus", "$9.99", "For one person", ["2 TB of storage", "Automatic backup", "30-day restore"], "Try free"], ["Essentials", "$18", "For professionals", ["3 TB of storage", "Share with controls", "Signatures", "180-day restore"], "Try free"], ["Business", "$15", "For teams, per user", ["9 TB for the team", "Admin console", "Team folders", "Audit log"], "Try free"]], per: "per month" } }),
  ];

  function dayIndex(date) {
    const d = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    return Math.round((d - START) / DAY);
  }
  function key(date) {
    const d = date || new Date();
    return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
  }
  function parse(k) {
    const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(k || "");
    return m ? new Date(+m[1], +m[2] - 1, +m[3]) : null;
  }
  function forDate(date) {
    const n = dayIndex(date);
    const brief = LIBRARY[((n % LIBRARY.length) + LIBRARY.length) % LIBRARY.length];
    return { ...brief, number: n + 1, mobbin: brief.mobbin || brief.product };
  }

  window.PDBriefs = { LIBRARY, forDate, key, parse };
})();
